config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_event,only: [:update,:destroy,:edit]

	def index
		@users =User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.save
		redirect_to root_path
	end

	def edit
	end

	def update
	    @user.update(user_params)
	    redirect_to root_path
	end

	def destroy
  	  @user.destroy
  	  redirect_to users_path
   end

   def set_event
   	@user = User.find(params[:id])
   end

    private
     def user_params
   	   params.require(:user).permit(:name,:age,:city)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormTagExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user  do |f| %>
<br>
<%= f.label 'Name' %>
<%= f.text_field :name%> <br><br>

<%= f.label 'City' %>
<%= f.text_field :city%> <br><br>

<%= f.label'Age' %>
<%= f.text_field :age%> <br><br>


<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h2>index</h2>

<h1>hello</h1>
<a href ="/users/new">New</a>
<table border=1>
<tr>
	<th>Name</th>
	<th>Age</th>
	<th>City</th>
	<th>Edit</th>
	<th>Delete</th>

</tr>
<% @users.each do |var| %>
  <tr>
	  <td><%=var.name%></td>
	  <td><%=var.age%></td>
	  <td><%=var.city%></td>
	  <td><%= link_to 'edit', edit_user_path(var.id) %></td>
	   <td><%= link_to 'delete',user_path(var),method: :delete,
	    data: { confirm:"are you sure" } %></td>
  </tr>
  <%end%>
</table>

app/views/users/new.html.erb
<%= form_for @user  do |f| %>
<br>
<%=f.label 'Name' %>
<%= f.text_field :name%> <br><br>

<%= f.label 'City' %>
<%= f.text_field :city%> <br><br>

<%= f.label'Age' %>
<%= f.text_field :age%> <br><br>


<%= f.submit %>
<% end %>